# Generated by Django 5.2.7 on 2025-11-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
